#   Want to test if Mito can replace the tideous work of writing code from scratch

Following things I will check and try to reproduce:
### From initial analysis we have found the following
-   3 columns with missimg values
-   Cabin has more than 70% missing data --> Maybe we can neglect it
-   Fare is highly skewed (Positive)
-   Survival rate of female was much higher than male
-   Age, Class, Gender shows promising prediciton power
-   Embarked has 3 unique categories
-   Descreet variables are skewed also

### Graphs
-   Relation between missing data vs survived
-   Male and female count in each class
-   Percentage of passenger survived
-   Female survival rate
-   Male survival rate
-   Passenger survived in each class
-   Age and Fare distribution
-   Cardinality check - 'Embarked', 'Cabin', 'Ticket', 'Name'
-   Ordinal values check - Pclass,  SibSp,   Parch

In [1]:
import mitosheet
mitosheet.sheet()

MitoWidget(analysis_data_json='{"analysisName": "UUID-57105057-9556-4ae8-b197-587c91ccc28f", "code": {"importsâ€¦

In [ ]:
# MITO CODE START (DO NOT EDIT)

from mitosheet import * # Import necessary functions from Mito
register_analysis('UUID-57105057-9556-4ae8-b197-587c91ccc28f') # Let Mito know which analysis is being run

# Imported D:\01_Projects\End-to-End-ML\Model_building\Dataset\train.csv
import pandas as pd
train_csv = pd.read_csv(r'D:\01_Projects\End-to-End-ML\Model_building\Dataset\train.csv')

# Added column new-column-illi to train_csv
train_csv.insert(6, 'new-column-illi', 0)

# Renamed new-column-illi to Age_Dummy in train_csv
train_csv.rename(columns={"new-column-illi": "Age_Dummy"}, inplace=True)

# Set new-column-illi in train_csv to = if(Age == 'NaN', 0,1) 
train_csv['Age_Dummy'] =  IF(train_csv['Age'] == 'NaN', 0,1)

# Sorted Age in train_csv in ascending order
train_csv = train_csv.sort_values(by='Age', ascending=True, na_position='first')

# Set new-column-illi in train_csv to = if(Age>0, 1,0) 
train_csv['Age_Dummy'] =  IF(train_csv['Age']>0, 1,0)

# Sorted Age in train_csv in descending order
train_csv = train_csv.sort_values(by='Age', ascending=False, na_position='last')

# Pivoted train_csv into df2
unused_columns = train_csv.columns.difference(set(['Age_Dummy']).union(set(['Survived'])).union(set({'Survived'})))
tmp_df = train_csv.drop(unused_columns, axis=1)
pivot_table = tmp_df.pivot_table(
    index=['Age_Dummy'],
    columns=['Survived'],
    values=['Survived'],
    aggfunc={'Survived': ['count']}
)

# Flatten the column headers
pivot_table.columns = [flatten_column_header(col) for col in pivot_table.columns.values]

# Reset the column name and the indexes
df2 = pivot_table.reset_index()

# Pivoted train_csv into df3
unused_columns = train_csv.columns.difference(set(['Pclass']).union(set(['Survived'])).union(set({'PassengerId'})))
tmp_df = train_csv.drop(unused_columns, axis=1)
pivot_table = tmp_df.pivot_table(
    index=['Pclass'],
    columns=['Survived'],
    values=['PassengerId'],
    aggfunc={'PassengerId': ['count']}
)

# Flatten the column headers
pivot_table.columns = [flatten_column_header(col) for col in pivot_table.columns.values]

# Reset the column name and the indexes
df3 = pivot_table.reset_index()

# Pivoted train_csv into df4
unused_columns = train_csv.columns.difference(set(['Sex']).union(set(['Survived'])).union(set({'PassengerId'})))
tmp_df = train_csv.drop(unused_columns, axis=1)
pivot_table = tmp_df.pivot_table(
    index=['Sex'],
    columns=['Survived'],
    values=['PassengerId'],
    aggfunc={'PassengerId': ['count']}
)

# Flatten the column headers
pivot_table.columns = [flatten_column_header(col) for col in pivot_table.columns.values]

# Reset the column name and the indexes
df4 = pivot_table.reset_index()

# Pivoted train_csv into df5
df5 = pd.DataFrame(data={})

# Pivoted train_csv into df5
unused_columns = train_csv.columns.difference(set([]).union(set(['Embarked'])).union(set({'PassengerId'})))
tmp_df = train_csv.drop(unused_columns, axis=1)
pivot_table = tmp_df.pivot_table(
    columns=['Embarked'],
    values=['PassengerId'],
    aggfunc={'PassengerId': [pd.Series.nunique]}
)

# Flatten the column headers
pivot_table.columns = [flatten_column_header(col) for col in pivot_table.columns.values]

# Reset the column name and the indexes
df5 = pivot_table.reset_index()

# Pivoted train_csv into df5
unused_columns = train_csv.columns.difference(set(['Embarked']).union(set([])).union(set({'PassengerId'})))
tmp_df = train_csv.drop(unused_columns, axis=1)
pivot_table = tmp_df.pivot_table(
    index=['Embarked'],
    values=['PassengerId'],
    aggfunc={'PassengerId': [pd.Series.nunique]}
)

# Flatten the column headers
pivot_table.columns = [flatten_column_header(col) for col in pivot_table.columns.values]

# Reset the column name and the indexes
df5 = pivot_table.reset_index()

# Pivoted train_csv into df6
df6 = pd.DataFrame(data={})

# Deleted dataframe df6
del df6

# Pivoted train_csv into df6
unused_columns = train_csv.columns.difference(set(['Name']).union(set([])).union(set({'Name'})))
tmp_df = train_csv.drop(unused_columns, axis=1)
pivot_table = tmp_df.pivot_table(
    index=['Name'],
    values=['Name'],
    aggfunc={'Name': [pd.Series.nunique]}
)

# Flatten the column headers
pivot_table.columns = [flatten_column_header(col) for col in pivot_table.columns.values]

# Reset the column name and the indexes
df6 = pivot_table.reset_index()

# Deleted dataframe df6
del df6

# Pivoted train_csv into df6
unused_columns = train_csv.columns.difference(set(['Pclass']).union(set(['Age_Dummy'])).union(set({'Survived'})))
tmp_df = train_csv.drop(unused_columns, axis=1)
pivot_table = tmp_df.pivot_table(
    index=['Pclass'],
    columns=['Age_Dummy'],
    values=['Survived'],
    aggfunc={'Survived': ['count']}
)

# Flatten the column headers
pivot_table.columns = [flatten_column_header(col) for col in pivot_table.columns.values]

# Reset the column name and the indexes
df6 = pivot_table.reset_index()

  
# MITO CODE END (DO NOT EDIT)